_target_: lightning.Trainer

default_root_dir: ${paths.output_dir}

min_epochs: 1 # prevents early stopping
max_epochs: 100

accelerator: auto
devices: 1

reload_dataloaders_every_n_epochs: 5


limit_train_batches: .4
limit_test_batches:  .4
limit_val_batches: 1

# mixed precision for extra speed-up
precision: 16
# precision: 32  # higher machine

# perform a validation loop every N training epochs
check_val_every_n_epoch: 1

# set True to to ensure deterministic results
# makes training slower but gives more reproducibility than just setting seeds
deterministic: False