# https://www.tensorflow.org/tensorboard/

tensorboard:
  _target_: lightning.pytorch.loggers.tensorboard.TensorBoardLogger
  save_dir: "${paths.output_dir}/tensorboard/"
  name: "bs-${data.batch_size}_depths-${model.depths}_dims-${model.dims}_head_fn-${model.head_fn}_conv_ratio-${model.conv_ratio}"
  log_graph: False
  default_hp_metric: True
  prefix: ""
  # version: ""